version: '3'
services:
     # React nginx project container
     app:
         build: 
           context: .
           dockerfile: docker/react/Dockerfile
         container_name: react
         ports:
           - "3000:3000"

         restart: always
         networks:
             - prod-environment

networks:
  prod-environment:
