version: '3'
services:
     # React nginx project container
     app:
         build: 
           context: .
           dockerfile: docker/react/Dockerfile
         container_name: react
         ports:
           - "3000:3000"
         environment:
             REACT_APP_URL_BACK: 'http://10.70.4.21:8741/api'
         restart: always
         networks:
             - prod-environment

networks:
  prod-environment: